/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: cboulonn <cboulonn@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2016/08/10 13:56:11 by cboulonn          #+#    #+#             */
/*   Updated: 2016/10/20 14:37:23 by cboulonn         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../includes/ft_printf.h"

int		main(void)
{
	char	*hi;
	char	*ret;
	int		pr;
	wchar_t	wchar;
	char	c;
	char	b;
	char	v;
	int		fd;

	c = 'c';
	b = 'd';
	v = 'v';
	wchar = L'正';
	hi = ft_strdup("Hello, world!");
	setlocale(LC_ALL, "en_US.UTF-8");
	ft_printf("****** Sans conversions ******\n");
	ft_printf("test : Bonjour tous le monde\n");
	pr = ft_printf("Bonjour tous le monde\n");
	ft_printf("%d\n", pr);
	ft_printf("test : Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.\n");
	pr = ft_printf("Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.Blablablabla blablabla blabla blablabla bla blablabla blablablabla bla.\n");
	ft_printf("%d\n", pr);
	pr = ft_printf("|%1010d|\n", 123456789);
	ft_printf("%d\n", pr);
	pr = ft_printf("|%1010s|\n", "123456789");
	ft_printf("%d\n", pr);
	pr = ft_printf("******************************\n\n");


	ft_printf("***** Conversion  simple *****\n");
	ft_printf("test : %%s, hi -> Hello, world!\n");
	pr = ft_printf("%s\n", hi);
	ft_printf("%d\n", pr);
	ft_printf("test : %%d, 75000\n");
	pr = ft_printf("%d\n", 75000);
	ft_printf("%d\n", pr);
	ft_printf("test : %%d, -2147483648\n");
	pr = ft_printf("%d\n", -2147483648);
	ft_printf("%d\n", pr);
	ft_printf("test : %%u, 75000\n");
	pr = ft_printf("%u\n", 75000);
	ft_printf("%d\n", pr);
	ft_printf("test : %%u, -4294967296\n");
	pr = ft_printf("%u\n", -4294967296);
	ft_printf("%d\n", pr);
	ft_printf("test : %%x, 75000\n");
	pr = ft_printf("%x\n", 75000);
	ft_printf("%d\n", pr);
	ft_printf("test : %%x, -4294967296\n");
	pr = ft_printf("%x\n", -4294967296);
	ft_printf("%d\n", pr);
	ft_printf("test : %%X, 75000\n");
	pr = ft_printf("%X\n", 75000);
	ft_printf("%d\n", pr);
	ft_printf("test : %%X, -4294967296\n");
	pr = ft_printf("%X\n", -4294967296);
	ft_printf("%d\n", pr);
	ft_printf("test : %%D, -75000\n");
	pr = ft_printf("%D\n", -75000);
	ft_printf("%d\n", pr);
	ft_printf("test : %%o, -75000\n");
	pr = ft_printf("%o\n", -75000);
	ft_printf("%d\n", pr);
	ft_printf("test : %%U, -75000\n");
	pr = ft_printf("%U\n", -75000);
	ft_printf("%d\n", pr);
	ft_printf("test : %%c, 100\n");
	pr = ft_printf("%c\n", 100);
	ft_printf("%d\n", pr);
	ft_printf("test : %%%%\n");
	pr = ft_printf("%%\n");
	ft_printf("%d\n", pr);
	ft_printf("test : %%d, 0\n");
	pr = ft_printf("%d\n", 0);
	ft_printf("%d\n", pr);
	ft_printf("test : %%x, 0\n");
	pr = ft_printf("%x\n", 0);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");


	ft_printf("********** Lenght  ***********\n");
	ft_printf("test : %%hhd, -151525\n");
	pr = ft_printf("%hhd\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%hd, -151525\n");
	pr = ft_printf("%hd\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%ld, -151525\n");
	pr = ft_printf("%ld\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%lld, -151525\n");
	pr = ft_printf("%lld\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%zd, -151525\n");
	pr = ft_printf("%zd\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%jd, -151525\n");
	pr = ft_printf("%jd\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%zd, -9223372036854775808\n");
	pr = ft_printf("%zd\n", -9223372036854775808);
	ft_printf("%d\n", pr);
	ft_printf("test : %%hhx, -151525\n");
	pr = ft_printf("%hhx\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%hx, -151525\n");
	pr = ft_printf("%hx\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%lx, -151525\n");
	pr = ft_printf("%lx\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%llx, -151525\n");
	pr = ft_printf("%llx\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%zx, -151525\n");
	pr = ft_printf("%zx\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%jx, -151525\n");
	pr = ft_printf("%jx\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%hhX, -151525\n");
	pr = ft_printf("%hhX\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%hX, -151525\n");
	pr = ft_printf("%hX\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%lX, -151525\n");
	pr = ft_printf("%lX\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%llX, -151525\n");
	pr = ft_printf("%llX\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%zX, -151525\n");
	pr = ft_printf("%zX\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%jX, -151525\n");
	pr = ft_printf("%jX\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%hhu, -151525\n");
	pr = ft_printf("%hhu\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%hu, -151525\n");
	pr = ft_printf("%hu\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%lu, -151525\n");
	pr = ft_printf("%lu\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%llu, -151525\n");
	pr = ft_printf("%llu\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%zu, -151525\n");
	pr = ft_printf("%zu\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("test : %%ju, -151525\n");
	pr = ft_printf("%ju\n", -151525);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");

	ft_printf("********** Flags & d *********\n");
	ft_printf("test : %%#d, -123456789\n");
	pr = ft_printf(":%#d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%+d, -123456789\n");
	pr = ft_printf(":%+d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %% d, -123456789\n");
	pr = ft_printf(":% d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %% +d, -123456789\n");
	pr = ft_printf(":% +d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%20d, -123456789\n");
	pr = ft_printf(":%20d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%020d, -123456789\n");
	pr = ft_printf(":%020d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%+20d, -123456789\n");
	pr = ft_printf(":%+20d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%+020d, -123456789\n");
	pr = ft_printf(":%+020d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-020d, -123456789\n");
	pr = ft_printf(":%-020d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#020.15d, -123456789\n");
	pr = ft_printf(":%#020.15d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#-020.15d, -123456789\n");
	pr = ft_printf(":%#-020.15d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-020.15d, -123456789\n");
	pr = ft_printf(":%-020.15d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#+020.15d, -123456789\n");
	pr = ft_printf(":%#+020.15d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#- 020.15d, -123456789\n");
	pr = ft_printf(":%#- 020.15d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#+020.5d, -123456789\n");
	pr = ft_printf(":%#+020.5d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#- 020.5d, -123456789\n");
	pr = ft_printf(":%#- 020.5d:\n", -123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#+020.5d, 123456789\n");
	pr = ft_printf(":%#+020.5d:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#- 020.5d, 123456789\n");
	pr = ft_printf(":%#- 020.5d:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");


	ft_printf("********** Flags & u *********\n");
	ft_printf("test : %%+u, 123456789\n");
	pr = ft_printf(":%+u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %% u, 123456789\n");
	pr = ft_printf(":% u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%20u, 123456789\n");
	pr = ft_printf(":%20u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-20u, 123456789\n");
	pr = ft_printf(":%-20u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%020u, 123456789\n");
	pr = ft_printf(":%020u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-020u, 123456789\n");
	pr = ft_printf(":%-020u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%20.15u, 123456789\n");
	pr = ft_printf(":%20.15u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-20.15u, 123456789\n");
	pr = ft_printf(":%-20.15u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#u, 123456789\n");
	pr = ft_printf(":%#u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#20u, 123456789\n");
	pr = ft_printf(":%#20u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#-20u, 123456789\n");
	pr = ft_printf(":%#-20u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#020u, 123456789\n");
	pr = ft_printf(":%#020u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#-020u, 123456789\n");
	pr = ft_printf(":%#-020u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#20.15u, 123456789\n");
	pr = ft_printf(":%#20.15u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#-20.15u, 123456789\n");
	pr = ft_printf(":%#-20.15u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#+020.5u, 123456789\n");
	pr = ft_printf(":%#+020.5u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#- 020.5u, 123456789\n");
	pr = ft_printf(":%#- 020.5u:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");


	ft_printf("******** Flags & x ***********\n");
	ft_printf("test : %%+x, 123456789\n");
	pr = ft_printf(":%+x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %% x, 123456789\n");
	pr = ft_printf(":% x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%20x, 123456789\n");
	pr = ft_printf(":%20x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-20x, 123456789\n");
	pr = ft_printf(":%-20x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%020x, 123456789\n");
	pr = ft_printf(":%020x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-020x, 123456789\n");
	pr = ft_printf(":%-020x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%20.15x, 123456789\n");
	pr = ft_printf(":%20.15x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-20.15x, 123456789\n");
	pr = ft_printf(":%-20.15x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#x, 123456789\n");
	pr = ft_printf(":%#x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#20x, 123456789\n");
	pr = ft_printf(":%#20x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#-20x, 123456789\n");
	pr = ft_printf(":%#-20x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#020x, 123456789\n");
	pr = ft_printf(":%#020x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#-020x, 123456789\n");
	pr = ft_printf(":%#-020x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#20.15x, 123456789\n");
	pr = ft_printf(":%#20.15x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#-20.15x, 123456789\n");
	pr = ft_printf(":%#-20.15x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#+020.5x, 123456789\n");
	pr = ft_printf(":%#+020.5x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#- 020.5x, 123456789\n");
	pr = ft_printf(":%#- 020.5x:\n", 123456789);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");

	ft_printf("******** Flags & p ***********\n");
	ft_printf("test : %%5p, 0\n");
	pr = ft_printf("%5p\n", 0);
	ft_printf("%d\n", pr);
	ft_printf("test : %%05p, 0\n");
	pr = ft_printf("%05p\n", 0);
	ft_printf("%d\n", pr);
	ft_printf("test : %%10.5p, 0\n");
	pr = ft_printf(":%10.5p:\n", 0);
	ft_printf("%d\n", pr);
	ft_printf("test : %%010.5p, 0\n");
	pr = ft_printf(":%010.5p:\n", 0);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-10.5p, 0\n");
	pr = ft_printf(":%-10.5p:\n", 0);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-010.5p, 0\n");
	pr = ft_printf(":%-010.5p:\n", 0);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");

	ft_printf("******** Flags & s ***********\n");
	ft_printf("test : %%10s, hi -> Hello, world!\n");
	pr = ft_printf(":%10s:\n", hi);
	ft_printf("%d\n", pr);
	ft_printf("test : %%020s, hi -> Hello, world!\n");
	pr = ft_printf(":%020s:\n", hi);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#20.10s, hi -> Hello, world!\n");
	pr = ft_printf(":%#20.10s:\n", hi);
	ft_printf("%d\n", pr);
	ft_printf("test : %% 20.10s, hi -> Hello, world!\n");
	pr = ft_printf(":% 20.10s:\n", hi);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-20.10s, hi -> Hello, world!\n");
	pr = ft_printf(":%-20.10s:\n", hi);
	ft_printf("%d\n", pr);
	ft_printf("test : %%+20.10s, hi -> Hello, world!\n");
	pr = ft_printf(":%+20.10s:\n", hi);
	ft_printf("%d\n", pr);
	ft_printf("test : %%10.20s, hi -> Hello, world!\n");
	pr = ft_printf(":%10.20s:\n", hi);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-10.20s, hi -> Hello, world!\n");
	pr = ft_printf(":%-10.20s:\n", hi);
	ft_printf("%d\n", pr);
	ft_printf("test : %%s, null\n");
	pr = ft_printf(":%s:\n", NULL);
	ft_printf("%d\n", pr);
	ft_printf("test : %%20.5s, null\n");
	pr = ft_printf(":%20.5s:\n", NULL);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-20.5s, null\n");
	pr = ft_printf(":%-20.5s:\n", NULL);
	ft_printf("%d\n", pr);
	ft_printf("test : %%S, %ls\n", L"正");
	pr = ft_printf("%ls\n", L"正");
	ft_printf("%d\n", pr);
	ft_printf("test : %%S, %ls\n", L"我是一只猫。");
	pr = ft_printf("%ls\n", L"我是一只猫。");
	ft_printf("%d\n", pr);
	ft_printf("test : %%010S, %ls\n", L"我是");
	pr = ft_printf(":%010ls:\n", L"我是");
	ft_printf("%d\n", pr);
	ft_printf("test : %%10.2S, %ls\n", L"我是一只猫。");
	pr = ft_printf(":%10.2ls:\n", L"我是一只猫。");
	ft_printf("%d\n", pr);
	ft_printf("test : %%10.3S, %ls\n", L"我是一只猫。");
	pr = ft_printf(":%10.3ls:\n", L"我是一只猫。");
	ft_printf("%d\n", pr);
	ft_printf("test : %%10.6S, %ls\n", L"我是一只猫。");
	pr = ft_printf(":%10.6ls:\n", L"我是一只猫。");
	ft_printf("%d\n", pr);
	ft_printf("test : %%10.9S, %ls\n", L"我是一只猫。");
	pr = ft_printf(":%10.9ls:\n", L"我是一只猫。");
	ft_printf("%d\n", pr);
	ft_printf("test : %%-10.2S, %ls\n", L"我是一只猫。");
	pr = ft_printf(":%-10.2ls:\n", L"我是一只猫。");
	ft_printf("%d\n", pr);
	ft_printf("test : %%-10.3S, %ls\n", L"我是一只猫。");
	pr = ft_printf(":%-10.3ls:\n", L"我是一只猫。");
	ft_printf("%d\n", pr);
	ft_printf("test : %%-10.6S, %ls\n", L"我是一只猫。");
	pr = ft_printf(":%-10.6ls:\n", L"我是一只猫。");
	ft_printf("%d\n", pr);
	ft_printf("test : %%-10.9S, %ls\n", L"我是一只猫。");
	pr = ft_printf(":%-10.9ls:\n", L"我是一只猫。");
	ft_printf("%d\n", pr);
	ft_printf("test : %%S, null\n");
	pr = ft_printf(":%ls:\n", NULL);
	ft_printf("%d\n", pr);
	ft_printf("test : %%20.5S, null\n");
	pr = ft_printf(":%20.5ls:\n", NULL);
	ft_printf("%d\n", pr);
	ft_printf("test : %%-20.5S, null\n");
	pr = ft_printf(":%-20.5ls:\n", NULL);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");

	ft_printf("******** C/c ***********\n");
	pr = ft_printf("Bonjour\n");
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%y|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%c|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%lc|\n", wchar);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%llc|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%hhc|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%hc|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%jc|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%zc|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%12c|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%12.2c|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%*.*c|\n",12, 2, c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%*.*c|\n",-12, -2, c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%2c %4c %6c| fin\n", c, b, v);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%05c|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%-5c|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%-05c|\n", c);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%012C fin|\n", wchar);
	ft_printf("%d\n", pr);
	pr = ft_printf("Bonjour |%012.2C fin|\n", wchar);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");

	ft_printf("******** Autres ***********\n");
	ft_printf("test : @moulitest: %%#.x %%#.0x, 0, 0\n");
	pr = ft_printf(":@moulitest: %#.x %#.0x:\n", 0, 0);
	ft_printf("%d\n", pr);
	ft_printf("test : @moulitest: %%#.d %%#.0d, 42, 43\n");
	pr = ft_printf(":@moulitest: %#.d %#.0d:\n", 42, 43);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#x, 0\n");
	pr = ft_printf(":%#x:\n", 0);
	ft_printf("%d\n", pr);
	ft_printf("test : %%+d, 0\n");
	pr = ft_printf(":%+d:\n", 0);
	ft_printf("%d\n", pr);
	pr = ft_printf("%5.2s is a string\n", "");
	ft_printf("%d\n", pr);
	pr = ft_printf("%.5d\n", 1234567);
	ft_printf("%d\n", pr);
	pr = ft_printf(NULL);
	ft_printf("%d\n", pr);
	pr = ft_printf("%10y\n");
	ft_printf("%d\n", pr);
	pr = ft_printf("%.10s\n", "yo");
	ft_printf("%d\n", pr);
	pr = ft_printf("%");
	ft_printf("%d\n", pr);
	pr = ft_printf("% Zoooo\n");
	ft_printf("%d\n", pr);
	pr = ft_printf("%D\n", -1L);
	ft_printf("%d\n", pr);
	pr = ft_printf("%D\n", 0L);
	ft_printf("%d\n", pr);
	pr = ft_printf("%D\n", 1L);
	ft_printf("%d\n", pr);
	pr = ft_printf("%D\n", 42L);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");

	ft_printf("******** ft_sprintf ***********\n");
	ret = ft_sprintf(":%#x:\n", 0);
	ft_printf("%s", ret);
	free(ret);
	ret = ft_sprintf(":%+d:\n", 0);
	ft_printf("%s", ret);
	free(ret);
	ret = ft_sprintf("%5.2s is a string\n", "");
	ft_printf("%s", ret);
	free(ret);
	ret = ft_sprintf("%.5d\n", 1234567);
	ft_printf("%s", ret);
	free(ret);
	ret = ft_sprintf(NULL);
	ft_printf("%s\n", ret);
	free(ret);
	ret = ft_sprintf("%y\n");
	ft_printf("%s", ret);
	free(ret);
	ft_printf("******************************\n\n");

	ft_printf("******** BONUS: ft_dprintf ***********\n");
	fd = open("file", O_WRONLY | O_TRUNC |O_CREAT, S_IRWXU);
	pr = ft_dprintf(fd, "%5.2s is a string\n", "");
	ft_printf("%d\n", pr);
	pr = ft_dprintf(fd, "%.5d\n", 1234567);
	ft_printf("%d\n", pr);
	pr = ft_dprintf(fd, NULL);
	ft_printf("%d\n", pr);
	pr = ft_dprintf(fd, "%y\n");
	ft_printf("%d\n", pr);
	pr = ft_dprintf(fd, "%  ");
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");
	close(fd);

	ft_printf("******** test couleur ***********\n");
	pr = ft_printf("\033[31;5mBonjour\033[m |%12.2c|\n", c);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");

	ft_printf("******** Bonus: binaire ***********\n");
	ft_printf("test : %%#-020b, 123\n");
	pr = ft_printf(":%#-020b:\n", 123);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#20.15b, 12345\n");
	pr = ft_printf(":%#20.15b:\n", 12345);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#-20.15b, 1234567\n");
	pr = ft_printf(":%#-20.15b:\n", 1234567);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#+020.5b, 12345689\n");
	pr = ft_printf(":%#+020.5b:\n", 12345689);
	ft_printf("%d\n", pr);
	ft_printf("test : %%#- 020.5b, 56789\n");
	pr = ft_printf(":%#- 020.5b:\n", 56789);
	ft_printf("%d\n", pr);
	ft_printf("******************************\n\n");
	free(hi);
	return (0);
}
